name: Deploy Next.js (export) to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: med-sepse
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_USER: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - name: Build & Export
        env:
          NODE_ENV: production
        run: |
          npm run build
          npm run export
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
